# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d8b9c63
_src_path: /home/runner/work/cookiecutter-api/cookiecutter-api
author: Sir Meowsalots
cloud_service: Azure Function App
health_endpoint: health
include_infrastructure: false
language: typescript
open_source_license: MIT license
project_description: Kitties got claws...beware
project_name: KittenClaws
resources:
-   container: animals
    endpoint: cats
    name: Cat
    operations:
    - list
    - get_by_id
    - create
    - update
    - delete
-   container: animals
    endpoint: dogs
    name: Dog
    operations:
    - list
    - get_by_id
    - create
    - replace
    - delete

